### ISSUE TITLE
Check potential journal/conference

### ISSUE THREAD

**Issue by JasperLS** [JasperLS/UFC_Fight_Predictions#8]
where to publish + article design restrictions

**Comment by MattisPHartwig** [comment]
This one has described a few options for sport analytics papers: http://www.sfu.ca/~tswartz/papers/publish.pdf

Conferences: 
http://www.mathsportinternational.com/conferences.html --> Abstract deadline 24.03, paper submission 24.05, Call ist aber noch unklar, da schreibe ich mal ne mail hin.

https://www.anziam.org.au/The+16th+Australasian+Conference+on+Mathematics+and+Computers+in+Sport --> Die sieht mega gut aus, aber ist erst nächstes jahr:D

Journals:

Journal of Quantitative Analysis in Sports (JQAS) -->20-30 pages 

Journal of Sports Analytics (JSA) --> Sieht gut aus wäre fast meine Präferenz. Auch unter 20 Seiten: https://www.iospress.nl/journal/journal-of-sports-analytics/#submission-of-manuscripts

**Comment by MattisPHartwig** [comment]
We aim for: Journal of Sports Analytics (JSA)
